[project]
name = "api-chamados"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "black>=25.1.0",
    "fastapi[standard]>=0.115.12",
    "pydantic>=2.11.3",
    "python-decouple>=3.8",
    "sqlalchemy>=2.0.40",
]
